### PR TITLE
Fix missing on load text

### PR DESCRIPTION
**Pull request by shamshirz**
Request for Review.

Is `zshrc.local` called everytime you open a shell?

### CODE REVIEW

**Comment by rjdellecese** [comment]
Thanks for your contribution @shamshirz, will get to this this week!

**Comment by rjdellecese** [comment]
I lied in that last comment... but this week for sure!

**Comment by shamshirz** [comment]
@shamshirz Please address this on the weekend, preferably 10/26

**Comment by shamshirz** [comment]
I can't access this branch anymore! I've become unforked

**Pull request closed without merging**
